### PR TITLE
fix(learn-unlearn): learn, unlearn

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
Closes https://github.com/azerothcore/mod-npc-free-professions/issues/9
Closes https://github.com/azerothcore/mod-npc-free-professions/issues/2

@Helias

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Ok but can you describe the change

refactor of the code + fix the unlearn issue?

**Comment by IntelligentQuantum** [comment]
> Ok but can you describe the change
> 
> refactor of the code + fix the unlearn issue?

Yeah

**Comment by BarbzYHOOL** [comment]
no new thing added?

**Comment by BarbzYHOOL** [comment]
```
fix(cpp): Able to relearn unlearned prof + code refactor #10

Closes #9
Closes #2
```
squash commit name for merging

**Comment by BarbzYHOOL** [comment]
wtf is that shitty title helias xDD

**Comment by Helias** [comment]
sorry man xD

**Pull request merged**
