### PR TITLE
Update ProfessionNPC.cpp

### PR DESCRIPTION
**Pull request by poszer**
Disabling fishing as secondary profession

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
?? explain

**Comment by BarbzYHOOL** [comment]
then make it so it can learn all secondary jobs instead, since they are unlimited anyway

rather teach all secondary jobs at once

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/mod-npc-free-professions/pull/5 related

**Comment by talamortis** [comment]
@poszer are you able to test #5 ?
Thanks.

**Comment by talamortis** [comment]
Thanks for testing, i will close this as its no longer needed now

**Pull request closed without merging**
